#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM  mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build

ARG BUILDCONFIG=RELEASE
ARG VERSION=1.0.0

COPY TweeterBook.csproj /build/

RUN dotnet restore ./build/TweeterBook.csproj

COPY . ./build/
WORKDIR /build/
RUN dotnet publish ./TweeterBook.csproj -c $BUILDCONFIG -o out /p:Version=$VERSION

FROM  mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app

COPY --from=build /build/out .

ENTRYPOINT ["dotnet", "Tweetbook.dll"] 